features:
- acquisition_credit_line
- acquisition_method
- color_b
- color_g
- color_r
- copyright_holder
- date_of_birth
- date_of_death
- dating_period
- dating_presenting_date
- dating_sorting_date
- dating_year_early
- dating_year_late
- hex
- historical_person_name
- maker_name
- material_name
- nationality
- object_collection_name
- percentage
- place_of_birth
- place_of_death
- principal_maker
- principal_maker_occupation_auctioneer
- principal_maker_occupation_bookseller
- principal_maker_occupation_designer
- principal_maker_occupation_draughtsman
- principal_maker_occupation_goldsmith
- principal_maker_occupation_instrument_maker
- principal_maker_occupation_jeweler
- principal_maker_occupation_painter
- principal_maker_occupation_print_maker
- principal_maker_occupation_printer
- principal_maker_occupation_publisher
- principal_maker_occupation_sculptor
- principal_or_first_maker
- productionPlaces
- production_place_name
- qualification
- ratio
- roles
- te_acquisition_credit_line_by_likes
- te_acquisition_method_by_likes
- te_copyright_holder_by_likes
- te_date_of_birth_by_likes
- te_date_of_death_by_likes
- te_dating_presenting_date_by_likes
- te_hex_by_likes
- te_historical_person_name_by_likes
- te_maker_name_by_likes
- te_material_name_by_likes
- te_nationality_by_likes
- te_object_collection_name_by_likes
- te_place_of_birth_by_likes
- te_place_of_death_by_likes
- te_principal_maker_by_likes
- te_principal_maker_occupation_auctioneer_by_likes
- te_principal_maker_occupation_bookseller_by_likes
- te_principal_maker_occupation_designer_by_likes
- te_principal_maker_occupation_draughtsman_by_likes
- te_principal_maker_occupation_goldsmith_by_likes
- te_principal_maker_occupation_instrument_maker_by_likes
- te_principal_maker_occupation_jeweler_by_likes
- te_principal_maker_occupation_painter_by_likes
- te_principal_maker_occupation_print_maker_by_likes
- te_principal_maker_occupation_printer_by_likes
- te_principal_maker_occupation_publisher_by_likes
- te_principal_maker_occupation_sculptor_by_likes
- te_principal_or_first_maker_by_likes
- te_productionPlaces_by_likes
- te_production_place_name_by_likes
- te_qualification_by_likes
- te_roles_by_likes
- te_technique_name_by_likes
- technique_name
