features:
- Navy_Model_Room
- acquisition_credit_line
- acquisition_method
- agg_color_b_max_by_object_id
- agg_color_b_mean_by_object_id
- agg_color_b_median_by_object_id
- agg_color_b_min_by_object_id
- agg_color_b_percentage_sum_by_object_id
- agg_color_b_std_by_object_id
- agg_color_g_max_by_object_id
- agg_color_g_mean_by_object_id
- agg_color_g_median_by_object_id
- agg_color_g_min_by_object_id
- agg_color_g_percentage_sum_by_object_id
- agg_color_g_std_by_object_id
- agg_color_h_max_by_object_id
- agg_color_h_mean_by_object_id
- agg_color_h_median_by_object_id
- agg_color_h_min_by_object_id
- agg_color_h_percentage_sum_by_object_id
- agg_color_h_std_by_object_id
- agg_color_r_max_by_object_id
- agg_color_r_mean_by_object_id
- agg_color_r_median_by_object_id
- agg_color_r_min_by_object_id
- agg_color_r_percentage_sum_by_object_id
- agg_color_r_std_by_object_id
- agg_color_s_max_by_object_id
- agg_color_s_mean_by_object_id
- agg_color_s_median_by_object_id
- agg_color_s_min_by_object_id
- agg_color_s_percentage_sum_by_object_id
- agg_color_s_std_by_object_id
- agg_color_v_max_by_object_id
- agg_color_v_mean_by_object_id
- agg_color_v_median_by_object_id
- agg_color_v_min_by_object_id
- agg_color_v_percentage_sum_by_object_id
- agg_color_v_std_by_object_id
- agg_dating_period_div_max_by_acquisition_credit_line
- agg_dating_period_div_max_by_acquisition_method
- agg_dating_period_div_max_by_copyright_holder
- agg_dating_period_div_max_by_dating_presenting_date
- agg_dating_period_div_max_by_principal_maker
- agg_dating_period_div_max_by_principal_or_first_maker
- agg_dating_period_div_mean_by_acquisition_credit_line
- agg_dating_period_div_mean_by_acquisition_method
- agg_dating_period_div_mean_by_copyright_holder
- agg_dating_period_div_mean_by_dating_presenting_date
- agg_dating_period_div_mean_by_principal_maker
- agg_dating_period_div_mean_by_principal_or_first_maker
- agg_dating_period_div_median_by_acquisition_credit_line
- agg_dating_period_div_median_by_acquisition_method
- agg_dating_period_div_median_by_copyright_holder
- agg_dating_period_div_median_by_dating_presenting_date
- agg_dating_period_div_median_by_principal_maker
- agg_dating_period_div_median_by_principal_or_first_maker
- agg_dating_period_div_min_by_acquisition_credit_line
- agg_dating_period_div_min_by_acquisition_method
- agg_dating_period_div_min_by_copyright_holder
- agg_dating_period_div_min_by_dating_presenting_date
- agg_dating_period_div_min_by_principal_maker
- agg_dating_period_div_min_by_principal_or_first_maker
- agg_dating_period_max_by_acquisition_credit_line
- agg_dating_period_max_by_acquisition_method
- agg_dating_period_max_by_copyright_holder
- agg_dating_period_max_by_dating_presenting_date
- agg_dating_period_max_by_principal_maker
- agg_dating_period_max_by_principal_or_first_maker
- agg_dating_period_mean_by_acquisition_credit_line
- agg_dating_period_mean_by_acquisition_method
- agg_dating_period_mean_by_copyright_holder
- agg_dating_period_mean_by_dating_presenting_date
- agg_dating_period_mean_by_principal_maker
- agg_dating_period_mean_by_principal_or_first_maker
- agg_dating_period_median_by_acquisition_credit_line
- agg_dating_period_median_by_acquisition_method
- agg_dating_period_median_by_copyright_holder
- agg_dating_period_median_by_dating_presenting_date
- agg_dating_period_median_by_principal_maker
- agg_dating_period_median_by_principal_or_first_maker
- agg_dating_period_min_by_acquisition_credit_line
- agg_dating_period_min_by_acquisition_method
- agg_dating_period_min_by_copyright_holder
- agg_dating_period_min_by_dating_presenting_date
- agg_dating_period_min_by_principal_maker
- agg_dating_period_min_by_principal_or_first_maker
- agg_dating_period_std_by_acquisition_credit_line
- agg_dating_period_std_by_acquisition_method
- agg_dating_period_std_by_copyright_holder
- agg_dating_period_std_by_dating_presenting_date
- agg_dating_period_std_by_principal_maker
- agg_dating_period_std_by_principal_or_first_maker
- agg_dating_sorting_date_div_max_by_acquisition_credit_line
- agg_dating_sorting_date_div_max_by_acquisition_method
- agg_dating_sorting_date_div_max_by_copyright_holder
- agg_dating_sorting_date_div_max_by_dating_presenting_date
- agg_dating_sorting_date_div_max_by_principal_maker
- agg_dating_sorting_date_div_max_by_principal_or_first_maker
- agg_dating_sorting_date_div_mean_by_acquisition_credit_line
- agg_dating_sorting_date_div_mean_by_acquisition_method
- agg_dating_sorting_date_div_mean_by_copyright_holder
- agg_dating_sorting_date_div_mean_by_dating_presenting_date
- agg_dating_sorting_date_div_mean_by_principal_maker
- agg_dating_sorting_date_div_mean_by_principal_or_first_maker
- agg_dating_sorting_date_div_median_by_acquisition_credit_line
- agg_dating_sorting_date_div_median_by_acquisition_method
- agg_dating_sorting_date_div_median_by_copyright_holder
- agg_dating_sorting_date_div_median_by_dating_presenting_date
- agg_dating_sorting_date_div_median_by_principal_maker
- agg_dating_sorting_date_div_median_by_principal_or_first_maker
- agg_dating_sorting_date_div_min_by_acquisition_credit_line
- agg_dating_sorting_date_div_min_by_acquisition_method
- agg_dating_sorting_date_div_min_by_copyright_holder
- agg_dating_sorting_date_div_min_by_dating_presenting_date
- agg_dating_sorting_date_div_min_by_principal_maker
- agg_dating_sorting_date_div_min_by_principal_or_first_maker
- agg_dating_sorting_date_max_by_acquisition_credit_line
- agg_dating_sorting_date_max_by_acquisition_method
- agg_dating_sorting_date_max_by_copyright_holder
- agg_dating_sorting_date_max_by_dating_presenting_date
- agg_dating_sorting_date_max_by_principal_maker
- agg_dating_sorting_date_max_by_principal_or_first_maker
- agg_dating_sorting_date_mean_by_acquisition_credit_line
- agg_dating_sorting_date_mean_by_acquisition_method
- agg_dating_sorting_date_mean_by_copyright_holder
- agg_dating_sorting_date_mean_by_dating_presenting_date
- agg_dating_sorting_date_mean_by_principal_maker
- agg_dating_sorting_date_mean_by_principal_or_first_maker
- agg_dating_sorting_date_median_by_acquisition_credit_line
- agg_dating_sorting_date_median_by_acquisition_method
- agg_dating_sorting_date_median_by_copyright_holder
- agg_dating_sorting_date_median_by_dating_presenting_date
- agg_dating_sorting_date_median_by_principal_maker
- agg_dating_sorting_date_median_by_principal_or_first_maker
- agg_dating_sorting_date_min_by_acquisition_credit_line
- agg_dating_sorting_date_min_by_acquisition_method
- agg_dating_sorting_date_min_by_copyright_holder
- agg_dating_sorting_date_min_by_dating_presenting_date
- agg_dating_sorting_date_min_by_principal_maker
- agg_dating_sorting_date_min_by_principal_or_first_maker
- agg_dating_sorting_date_std_by_acquisition_credit_line
- agg_dating_sorting_date_std_by_acquisition_method
- agg_dating_sorting_date_std_by_copyright_holder
- agg_dating_sorting_date_std_by_dating_presenting_date
- agg_dating_sorting_date_std_by_principal_maker
- agg_dating_sorting_date_std_by_principal_or_first_maker
- agg_dating_year_early_div_max_by_acquisition_credit_line
- agg_dating_year_early_div_max_by_acquisition_method
- agg_dating_year_early_div_max_by_copyright_holder
- agg_dating_year_early_div_max_by_dating_presenting_date
- agg_dating_year_early_div_max_by_principal_maker
- agg_dating_year_early_div_max_by_principal_or_first_maker
- agg_dating_year_early_div_mean_by_acquisition_credit_line
- agg_dating_year_early_div_mean_by_acquisition_method
- agg_dating_year_early_div_mean_by_copyright_holder
- agg_dating_year_early_div_mean_by_dating_presenting_date
- agg_dating_year_early_div_mean_by_principal_maker
- agg_dating_year_early_div_mean_by_principal_or_first_maker
- agg_dating_year_early_div_median_by_acquisition_credit_line
- agg_dating_year_early_div_median_by_acquisition_method
- agg_dating_year_early_div_median_by_copyright_holder
- agg_dating_year_early_div_median_by_dating_presenting_date
- agg_dating_year_early_div_median_by_principal_maker
- agg_dating_year_early_div_median_by_principal_or_first_maker
- agg_dating_year_early_div_min_by_acquisition_credit_line
- agg_dating_year_early_div_min_by_acquisition_method
- agg_dating_year_early_div_min_by_copyright_holder
- agg_dating_year_early_div_min_by_dating_presenting_date
- agg_dating_year_early_div_min_by_principal_maker
- agg_dating_year_early_div_min_by_principal_or_first_maker
- agg_dating_year_early_max_by_acquisition_credit_line
- agg_dating_year_early_max_by_acquisition_method
- agg_dating_year_early_max_by_copyright_holder
- agg_dating_year_early_max_by_dating_presenting_date
- agg_dating_year_early_max_by_principal_maker
- agg_dating_year_early_max_by_principal_or_first_maker
- agg_dating_year_early_mean_by_acquisition_credit_line
- agg_dating_year_early_mean_by_acquisition_method
- agg_dating_year_early_mean_by_copyright_holder
- agg_dating_year_early_mean_by_dating_presenting_date
- agg_dating_year_early_mean_by_principal_maker
- agg_dating_year_early_mean_by_principal_or_first_maker
- agg_dating_year_early_median_by_acquisition_credit_line
- agg_dating_year_early_median_by_acquisition_method
- agg_dating_year_early_median_by_copyright_holder
- agg_dating_year_early_median_by_dating_presenting_date
- agg_dating_year_early_median_by_principal_maker
- agg_dating_year_early_median_by_principal_or_first_maker
- agg_dating_year_early_min_by_acquisition_credit_line
- agg_dating_year_early_min_by_acquisition_method
- agg_dating_year_early_min_by_copyright_holder
- agg_dating_year_early_min_by_dating_presenting_date
- agg_dating_year_early_min_by_principal_maker
- agg_dating_year_early_min_by_principal_or_first_maker
- agg_dating_year_early_std_by_acquisition_credit_line
- agg_dating_year_early_std_by_acquisition_method
- agg_dating_year_early_std_by_copyright_holder
- agg_dating_year_early_std_by_dating_presenting_date
- agg_dating_year_early_std_by_principal_maker
- agg_dating_year_early_std_by_principal_or_first_maker
- agg_dating_year_late_div_max_by_acquisition_credit_line
- agg_dating_year_late_div_max_by_acquisition_method
- agg_dating_year_late_div_max_by_copyright_holder
- agg_dating_year_late_div_max_by_dating_presenting_date
- agg_dating_year_late_div_max_by_principal_maker
- agg_dating_year_late_div_max_by_principal_or_first_maker
- agg_dating_year_late_div_mean_by_acquisition_credit_line
- agg_dating_year_late_div_mean_by_acquisition_method
- agg_dating_year_late_div_mean_by_copyright_holder
- agg_dating_year_late_div_mean_by_dating_presenting_date
- agg_dating_year_late_div_mean_by_principal_maker
- agg_dating_year_late_div_mean_by_principal_or_first_maker
- agg_dating_year_late_div_median_by_acquisition_credit_line
- agg_dating_year_late_div_median_by_acquisition_method
- agg_dating_year_late_div_median_by_copyright_holder
- agg_dating_year_late_div_median_by_dating_presenting_date
- agg_dating_year_late_div_median_by_principal_maker
- agg_dating_year_late_div_median_by_principal_or_first_maker
- agg_dating_year_late_div_min_by_acquisition_credit_line
- agg_dating_year_late_div_min_by_acquisition_method
- agg_dating_year_late_div_min_by_copyright_holder
- agg_dating_year_late_div_min_by_dating_presenting_date
- agg_dating_year_late_div_min_by_principal_maker
- agg_dating_year_late_div_min_by_principal_or_first_maker
- agg_dating_year_late_max_by_acquisition_credit_line
- agg_dating_year_late_max_by_acquisition_method
- agg_dating_year_late_max_by_copyright_holder
- agg_dating_year_late_max_by_dating_presenting_date
- agg_dating_year_late_max_by_principal_maker
- agg_dating_year_late_max_by_principal_or_first_maker
- agg_dating_year_late_mean_by_acquisition_credit_line
- agg_dating_year_late_mean_by_acquisition_method
- agg_dating_year_late_mean_by_copyright_holder
- agg_dating_year_late_mean_by_dating_presenting_date
- agg_dating_year_late_mean_by_principal_maker
- agg_dating_year_late_mean_by_principal_or_first_maker
- agg_dating_year_late_median_by_acquisition_credit_line
- agg_dating_year_late_median_by_acquisition_method
- agg_dating_year_late_median_by_copyright_holder
- agg_dating_year_late_median_by_dating_presenting_date
- agg_dating_year_late_median_by_principal_maker
- agg_dating_year_late_median_by_principal_or_first_maker
- agg_dating_year_late_min_by_acquisition_credit_line
- agg_dating_year_late_min_by_acquisition_method
- agg_dating_year_late_min_by_copyright_holder
- agg_dating_year_late_min_by_dating_presenting_date
- agg_dating_year_late_min_by_principal_maker
- agg_dating_year_late_min_by_principal_or_first_maker
- agg_dating_year_late_std_by_acquisition_credit_line
- agg_dating_year_late_std_by_acquisition_method
- agg_dating_year_late_std_by_copyright_holder
- agg_dating_year_late_std_by_dating_presenting_date
- agg_dating_year_late_std_by_principal_maker
- agg_dating_year_late_std_by_principal_or_first_maker
- agg_percentage_max_by_object_id
- agg_percentage_mean_by_object_id
- agg_percentage_median_by_object_id
- agg_percentage_min_by_object_id
- agg_percentage_std_by_object_id
- copyright_holder
- dating_period
- dating_presenting_date
- dating_sorting_date
- dating_year_early
- dating_year_late
- dollhouse
- drawings
- glass
- jewellery
- lace
- lda_historical_person_name_by_object_id_0
- lda_historical_person_name_by_object_id_1
- lda_historical_person_name_by_object_id_2
- lda_historical_person_name_by_object_id_3
- lda_historical_person_name_by_object_id_4
- lda_historical_person_name_by_object_id_5
- lda_historical_person_name_by_object_id_6
- lda_historical_person_name_by_object_id_7
- lda_historical_person_name_by_object_id_8
- lda_historical_person_name_by_object_id_9
- lda_material_by_object_id_0
- lda_material_by_object_id_1
- lda_material_by_object_id_2
- lda_material_by_object_id_3
- lda_material_by_object_id_4
- lda_material_by_object_id_5
- lda_material_by_object_id_6
- lda_material_by_object_id_7
- lda_material_by_object_id_8
- lda_material_by_object_id_9
- musical_instruments
- paintings
- paper
- principal_maker
- principal_or_first_maker
- prints
- te_acquisition_credit_line_by_likes
- te_acquisition_method_by_likes
- te_copyright_holder_by_likes
- te_dating_presenting_date_by_likes
- te_principal_maker_by_likes
- te_principal_or_first_maker_by_likes
