common:
    seed: &seed 2021
    metrics:
        name: rmsle
        params: {}
    drop:

data:
    loader:
        train:
            data_type: train
            reduce: False
        test:
            data_type: test
            reduce: False
    features:
        name: custom_002
        cat_features:
        oof:
            name:
    target:
        name: likes
        convert_type: log1p
        reconvert_type: expm1
    adversarial_validation: False

validation:
    name: GroupKFold
    params:
        n_splits: 7
    split:
        y: likes
        groups: art_series_id
    weight: average
    single: False

model:
    name: lightgbm
    task_type: regression
    params:
        boosting_type: gbdt
        objective: regression
        metric: rmse
        learning_rate: 0.01
        num_leaves: 130
        min_child_samples: 20
        feature_fraction: 0.7
        bagging_fraction: 0.8
        bagging_freq: 1
        bagging_seed: 11
        lambda_l1: 0.0
        lambda_l2: 0.0
        max_bin: 255
        verbose: -1
        nthread: -1
        seed: *seed
        first_metric_only: True
    num_boost_round: 10_000
    verbose_eval: 200
    early_stopping_rounds: 200
    feval:
    fobj:
    imp_type: gain